image_resource:
  type: docker-image
  source:
    repository: ansible/ubuntu14.04-ansible
    tag: stable

platform: linux

inputs:
  - name: online-systems

run:
  path: ./online-systems/ci/test.sh
